"""Generated metric registry — DO NOT EDIT BY HAND.

Regenerate with:
    python scripts/generate_metric_registry.py

Extracted from kio-simulator/kio_simulator.py by scripts/generate_metric_registry.py.
tests/metrics_api_tests/test_registry_drift.py fails if this file and the
simulator disagree.

Fields that are NOT derivable from the simulator (D1.1 baseline/target/direction
for KPI metrics, and the human-readable KPI names) are layered on separately in
registry.py — they come from docs/KPI_Metrik_Referansi_v1.3.docx, not from code.
"""

METRICS = {'kio.fix.attempt_count': {'otel_name': 'kio.fix.attempt_count',
                           'prom_name': 'kio_fix_attempt_count',
                           'instrument': 'counter',
                           'unit': '1',
                           'family': 'kpi',
                           'roles': ['bugfix'],
                           'optional': True,
                           'requires_task_type': [],
                           'labels': ['kio_id', 'llm', 'outcome', 'source', 'task_type'],
                           'required_group_by': ['outcome'],
                           'supports_source': True},
 'kio.heartbeat': {'otel_name': 'kio.heartbeat',
                   'prom_name': 'kio_heartbeat',
                   'instrument': 'counter',
                   'unit': '1',
                   'family': 'operational',
                   'roles': [],
                   'optional': False,
                   'requires_task_type': [],
                   'labels': ['kio_id', 'llm', 'task_type'],
                   'required_group_by': [],
                   'supports_source': False},
 'kio.kpi.active_usage.pct': {'otel_name': 'kio.kpi.active_usage.pct',
                              'prom_name': 'kio_kpi_active_usage_pct',
                              'instrument': 'histogram',
                              'unit': '%',
                              'family': 'kpi',
                              'roles': ['adoption'],
                              'optional': True,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                              'required_group_by': [],
                              'supports_source': True},
 'kio.kpi.adoption_rate.pct': {'otel_name': 'kio.kpi.adoption_rate.pct',
                               'prom_name': 'kio_kpi_adoption_rate_pct',
                               'instrument': 'histogram',
                               'unit': '%',
                               'family': 'kpi',
                               'roles': ['adoption'],
                               'optional': True,
                               'requires_task_type': [],
                               'labels': ['kio_id', 'llm', 'source', 'task_type'],
                               'required_group_by': [],
                               'supports_source': True},
 'kio.kpi.annual_cost.pct_of_baseline': {'otel_name': 'kio.kpi.annual_cost.pct_of_baseline',
                                         'prom_name': 'kio_kpi_annual_cost_pct_of_baseline',
                                         'instrument': 'histogram',
                                         'unit': '%',
                                         'family': 'kpi',
                                         'roles': ['ai-sysdev'],
                                         'optional': True,
                                         'requires_task_type': [],
                                         'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                         'required_group_by': [],
                                         'supports_source': True},
 'kio.kpi.bugfix_time.pct_of_baseline': {'otel_name': 'kio.kpi.bugfix_time.pct_of_baseline',
                                         'prom_name': 'kio_kpi_bugfix_time_pct_of_baseline',
                                         'instrument': 'histogram',
                                         'unit': '%',
                                         'family': 'kpi',
                                         'roles': ['bugfix'],
                                         'optional': True,
                                         'requires_task_type': [],
                                         'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                         'required_group_by': [],
                                         'supports_source': True},
 'kio.kpi.code_quality.pct_of_baseline': {'otel_name': 'kio.kpi.code_quality.pct_of_baseline',
                                          'prom_name': 'kio_kpi_code_quality_pct_of_baseline',
                                          'instrument': 'histogram',
                                          'unit': '%',
                                          'family': 'kpi',
                                          'roles': ['nlp-requirements', 'architecture-to-code'],
                                          'optional': True,
                                          'requires_task_type': [],
                                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                          'required_group_by': [],
                                          'supports_source': True},
 'kio.kpi.codegen_speed.pct_of_baseline': {'otel_name': 'kio.kpi.codegen_speed.pct_of_baseline',
                                           'prom_name': 'kio_kpi_codegen_speed_pct_of_baseline',
                                           'instrument': 'histogram',
                                           'unit': '%',
                                           'family': 'kpi',
                                           'roles': ['nlp-requirements', 'architecture-to-code'],
                                           'optional': True,
                                           'requires_task_type': [],
                                           'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                           'required_group_by': [],
                                           'supports_source': True},
 'kio.kpi.cross_arch_build.success_count': {'otel_name': 'kio.kpi.cross_arch_build.success_count',
                                            'prom_name': 'kio_kpi_cross_arch_build_success_count',
                                            'instrument': 'counter',
                                            'unit': '1',
                                            'family': 'kpi',
                                            'roles': ['green-deploy'],
                                            'optional': True,
                                            'requires_task_type': [],
                                            'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                            'required_group_by': [],
                                            'supports_source': True},
 'kio.kpi.customer_reported_issues.pct_of_baseline': {'otel_name': 'kio.kpi.customer_reported_issues.pct_of_baseline',
                                                      'prom_name': 'kio_kpi_customer_reported_issues_pct_of_baseline',
                                                      'instrument': 'histogram',
                                                      'unit': '%',
                                                      'family': 'kpi',
                                                      'roles': ['bugfix'],
                                                      'optional': True,
                                                      'requires_task_type': [],
                                                      'labels': ['kio_id',
                                                                 'llm',
                                                                 'source',
                                                                 'task_type'],
                                                      'required_group_by': [],
                                                      'supports_source': True},
 'kio.kpi.deploy_energy_efficiency.pct_of_baseline': {'otel_name': 'kio.kpi.deploy_energy_efficiency.pct_of_baseline',
                                                      'prom_name': 'kio_kpi_deploy_energy_efficiency_pct_of_baseline',
                                                      'instrument': 'histogram',
                                                      'unit': '%',
                                                      'family': 'kpi',
                                                      'roles': ['green-deploy'],
                                                      'optional': True,
                                                      'requires_task_type': [],
                                                      'labels': ['kio_id',
                                                                 'llm',
                                                                 'source',
                                                                 'task_type'],
                                                      'required_group_by': [],
                                                      'supports_source': True},
 'kio.kpi.dev_productivity.pct_of_baseline': {'otel_name': 'kio.kpi.dev_productivity.pct_of_baseline',
                                              'prom_name': 'kio_kpi_dev_productivity_pct_of_baseline',
                                              'instrument': 'histogram',
                                              'unit': '%',
                                              'family': 'kpi',
                                              'roles': ['ai-sysdev'],
                                              'optional': True,
                                              'requires_task_type': [],
                                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                              'required_group_by': [],
                                              'supports_source': True},
 'kio.kpi.issue_resolution.pct_of_baseline': {'otel_name': 'kio.kpi.issue_resolution.pct_of_baseline',
                                              'prom_name': 'kio_kpi_issue_resolution_pct_of_baseline',
                                              'instrument': 'histogram',
                                              'unit': '%',
                                              'family': 'kpi',
                                              'roles': ['bugfix'],
                                              'optional': True,
                                              'requires_task_type': [],
                                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                              'required_group_by': [],
                                              'supports_source': True},
 'kio.kpi.lifecycle_energy.pct_of_baseline': {'otel_name': 'kio.kpi.lifecycle_energy.pct_of_baseline',
                                              'prom_name': 'kio_kpi_lifecycle_energy_pct_of_baseline',
                                              'instrument': 'histogram',
                                              'unit': '%',
                                              'family': 'kpi',
                                              'roles': ['green-deploy'],
                                              'optional': True,
                                              'requires_task_type': [],
                                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                              'required_group_by': [],
                                              'supports_source': True},
 'kio.kpi.refactoring_effort.pct_of_baseline': {'otel_name': 'kio.kpi.refactoring_effort.pct_of_baseline',
                                                'prom_name': 'kio_kpi_refactoring_effort_pct_of_baseline',
                                                'instrument': 'histogram',
                                                'unit': '%',
                                                'family': 'kpi',
                                                'roles': ['ai-sysdev'],
                                                'optional': True,
                                                'requires_task_type': [],
                                                'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                                'required_group_by': [],
                                                'supports_source': True},
 'kio.kpi.review_score.pct_of_baseline': {'otel_name': 'kio.kpi.review_score.pct_of_baseline',
                                          'prom_name': 'kio_kpi_review_score_pct_of_baseline',
                                          'instrument': 'histogram',
                                          'unit': '%',
                                          'family': 'kpi',
                                          'roles': ['architecture-to-code'],
                                          'optional': True,
                                          'requires_task_type': [],
                                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                          'required_group_by': [],
                                          'supports_source': True},
 'kio.kpi.satisfaction.mos': {'otel_name': 'kio.kpi.satisfaction.mos',
                              'prom_name': 'kio_kpi_satisfaction_mos',
                              'instrument': 'histogram',
                              'unit': '1',
                              'family': 'kpi',
                              'roles': ['adoption'],
                              'optional': True,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                              'required_group_by': [],
                              'supports_source': True},
 'kio.kpi.technical_debt.pct_of_baseline': {'otel_name': 'kio.kpi.technical_debt.pct_of_baseline',
                                            'prom_name': 'kio_kpi_technical_debt_pct_of_baseline',
                                            'instrument': 'histogram',
                                            'unit': '%',
                                            'family': 'kpi',
                                            'roles': ['ai-sysdev'],
                                            'optional': True,
                                            'requires_task_type': [],
                                            'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                            'required_group_by': [],
                                            'supports_source': True},
 'kio.kpi.time_to_market.pct_of_baseline': {'otel_name': 'kio.kpi.time_to_market.pct_of_baseline',
                                            'prom_name': 'kio_kpi_time_to_market_pct_of_baseline',
                                            'instrument': 'histogram',
                                            'unit': '%',
                                            'family': 'kpi',
                                            'roles': ['ai-sysdev'],
                                            'optional': True,
                                            'requires_task_type': [],
                                            'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                            'required_group_by': [],
                                            'supports_source': True},
 'kio.llm.cost_usd': {'otel_name': 'kio.llm.cost_usd',
                      'prom_name': 'kio_llm_cost_usd',
                      'instrument': 'counter',
                      'unit': 'USD',
                      'family': 'operational',
                      'roles': [],
                      'optional': False,
                      'requires_task_type': [],
                      'labels': ['kio_id', 'llm', 'source', 'task_type'],
                      'required_group_by': [],
                      'supports_source': True},
 'kio.llm.energy_joules': {'otel_name': 'kio.llm.energy_joules',
                           'prom_name': 'kio_llm_energy_joules',
                           'instrument': 'counter',
                           'unit': 'J',
                           'family': 'operational',
                           'roles': [],
                           'optional': False,
                           'requires_task_type': [],
                           'labels': ['kio_id', 'llm', 'source', 'task_type'],
                           'required_group_by': [],
                           'supports_source': True},
 'kio.llm.gpu_temperature_celsius': {'otel_name': 'kio.llm.gpu_temperature_celsius',
                                     'prom_name': 'kio_llm_gpu_temperature_celsius',
                                     'instrument': 'histogram',
                                     'unit': 'Cel',
                                     'family': 'operational',
                                     'roles': [],
                                     'optional': False,
                                     'requires_task_type': [],
                                     'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                     'required_group_by': [],
                                     'supports_source': True},
 'kio.llm.token_count': {'otel_name': 'kio.llm.token_count',
                         'prom_name': 'kio_llm_token_count',
                         'instrument': 'counter',
                         'unit': 'tokens',
                         'family': 'operational',
                         'roles': [],
                         'optional': False,
                         'requires_task_type': [],
                         'labels': ['direction', 'kio_id', 'llm', 'source', 'task_type'],
                         'required_group_by': ['direction'],
                         'supports_source': True},
 'kio.llm.tokens_per_second': {'otel_name': 'kio.llm.tokens_per_second',
                               'prom_name': 'kio_llm_tokens_per_second',
                               'instrument': 'histogram',
                               'unit': 'tokens/s',
                               'family': 'operational',
                               'roles': [],
                               'optional': False,
                               'requires_task_type': [],
                               'labels': ['kio_id', 'llm', 'source', 'task_type'],
                               'required_group_by': [],
                               'supports_source': True},
 'kio.repo.directory_count': {'otel_name': 'kio.repo.directory_count',
                              'prom_name': 'kio_repo_directory_count',
                              'instrument': 'gauge',
                              'unit': '1',
                              'family': 'operational',
                              'roles': [],
                              'optional': True,
                              'requires_task_type': ['code-analysis'],
                              'labels': ['kio_id', 'llm', 'task_type'],
                              'required_group_by': [],
                              'supports_source': False},
 'kio.repo.file_count': {'otel_name': 'kio.repo.file_count',
                         'prom_name': 'kio_repo_file_count',
                         'instrument': 'gauge',
                         'unit': '1',
                         'family': 'operational',
                         'roles': [],
                         'optional': True,
                         'requires_task_type': ['code-analysis'],
                         'labels': ['kio_id', 'llm', 'task_type'],
                         'required_group_by': [],
                         'supports_source': False},
 'kio.repo.line_count': {'otel_name': 'kio.repo.line_count',
                         'prom_name': 'kio_repo_line_count',
                         'instrument': 'gauge',
                         'unit': '1',
                         'family': 'operational',
                         'roles': [],
                         'optional': True,
                         'requires_task_type': ['code-analysis'],
                         'labels': ['kio_id', 'llm', 'task_type'],
                         'required_group_by': [],
                         'supports_source': False},
 'kio.request.accuracy': {'otel_name': 'kio.request.accuracy',
                          'prom_name': 'kio_request_accuracy',
                          'instrument': 'histogram',
                          'unit': '1',
                          'family': 'operational',
                          'roles': [],
                          'optional': False,
                          'requires_task_type': [],
                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                          'required_group_by': [],
                          'supports_source': True},
 'kio.request.count': {'otel_name': 'kio.request.count',
                       'prom_name': 'kio_request_count',
                       'instrument': 'counter',
                       'unit': '1',
                       'family': 'operational',
                       'roles': [],
                       'optional': False,
                       'requires_task_type': [],
                       'labels': ['kio_id', 'llm', 'source', 'status', 'task_type'],
                       'required_group_by': ['status'],
                       'supports_source': True},
 'kio.request.duration_ms': {'otel_name': 'kio.request.duration_ms',
                             'prom_name': 'kio_request_duration_ms',
                             'instrument': 'histogram',
                             'unit': 'ms',
                             'family': 'operational',
                             'roles': [],
                             'optional': False,
                             'requires_task_type': [],
                             'labels': ['kio_id', 'llm', 'source', 'task_type'],
                             'required_group_by': [],
                             'supports_source': True},
 'kio.request.error_count': {'otel_name': 'kio.request.error_count',
                             'prom_name': 'kio_request_error_count',
                             'instrument': 'counter',
                             'unit': '1',
                             'family': 'operational',
                             'roles': [],
                             'optional': False,
                             'requires_task_type': [],
                             'labels': ['error_type', 'kio_id', 'llm', 'source', 'task_type'],
                             'required_group_by': ['error_type'],
                             'supports_source': True},
 'kio.session.active_count': {'otel_name': 'kio.session.active_count',
                              'prom_name': 'kio_session_active_count',
                              'instrument': 'up_down_counter',
                              'unit': '1',
                              'family': 'operational',
                              'roles': [],
                              'optional': False,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'task_type'],
                              'required_group_by': [],
                              'supports_source': False},
 'kio.slicing.success_rate': {'otel_name': 'kio.slicing.success_rate',
                              'prom_name': 'kio_slicing_success_rate',
                              'instrument': 'histogram',
                              'unit': '1',
                              'family': 'kpi',
                              'roles': ['bugfix'],
                              'optional': True,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                              'required_group_by': [],
                              'supports_source': True}}
