"""Generated metric registry — DO NOT EDIT BY HAND.

Regenerate with:
    python scripts/generate_metric_registry.py

Extracted from kio-simulator/kio_simulator.py by scripts/generate_metric_registry.py.
tests/metrics_api_tests/test_registry_drift.py fails if this file and the
simulator disagree.

Fields that are NOT derivable from the simulator (D1.1 baseline/target/direction
for KPI metrics, and the human-readable KPI names) are layered on separately in
registry.py — they come from docs/KPI_Metrik_Referansi_v1.3.docx, not from code.
"""

METRICS = {'kio.adoption.active_user_pct': {'otel_name': 'kio.adoption.active_user_pct',
                                  'prom_name': 'kio_adoption_active_user_pct',
                                  'instrument': 'histogram',
                                  'unit': '%',
                                  'family': 'kpi',
                                  'roles': ['adoption'],
                                  'optional': True,
                                  'requires_task_type': [],
                                  'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                  'required_group_by': [],
                                  'supports_source': True},
 'kio.adoption.mos_score': {'otel_name': 'kio.adoption.mos_score',
                            'prom_name': 'kio_adoption_mos_score',
                            'instrument': 'histogram',
                            'unit': '1',
                            'family': 'kpi',
                            'roles': ['adoption'],
                            'optional': True,
                            'requires_task_type': [],
                            'labels': ['kio_id', 'llm', 'source', 'task_type'],
                            'required_group_by': [],
                            'supports_source': True},
 'kio.adoption.usage_pct': {'otel_name': 'kio.adoption.usage_pct',
                            'prom_name': 'kio_adoption_usage_pct',
                            'instrument': 'histogram',
                            'unit': '%',
                            'family': 'kpi',
                            'roles': ['adoption'],
                            'optional': True,
                            'requires_task_type': [],
                            'labels': ['kio_id', 'llm', 'source', 'task_type'],
                            'required_group_by': [],
                            'supports_source': True},
 'kio.bugfix.duration_hours': {'otel_name': 'kio.bugfix.duration_hours',
                               'prom_name': 'kio_bugfix_duration_hours',
                               'instrument': 'histogram',
                               'unit': 'h',
                               'family': 'kpi',
                               'roles': ['bugfix'],
                               'optional': True,
                               'requires_task_type': [],
                               'labels': ['kio_id', 'llm', 'source', 'task_type'],
                               'required_group_by': [],
                               'supports_source': True},
 'kio.code_quality.score_pct': {'otel_name': 'kio.code_quality.score_pct',
                                'prom_name': 'kio_code_quality_score_pct',
                                'instrument': 'histogram',
                                'unit': '%',
                                'family': 'kpi',
                                'roles': ['nlp-requirements', 'architecture-to-code'],
                                'optional': True,
                                'requires_task_type': [],
                                'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                'required_group_by': [],
                                'supports_source': True},
 'kio.codegen.duration_minutes': {'otel_name': 'kio.codegen.duration_minutes',
                                  'prom_name': 'kio_codegen_duration_minutes',
                                  'instrument': 'histogram',
                                  'unit': 'min',
                                  'family': 'kpi',
                                  'roles': ['nlp-requirements', 'architecture-to-code'],
                                  'optional': True,
                                  'requires_task_type': [],
                                  'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                  'required_group_by': [],
                                  'supports_source': True},
 'kio.cost_saving.pct': {'otel_name': 'kio.cost_saving.pct',
                         'prom_name': 'kio_cost_saving_pct',
                         'instrument': 'histogram',
                         'unit': '%',
                         'family': 'kpi',
                         'roles': ['ai-sysdev'],
                         'optional': True,
                         'requires_task_type': [],
                         'labels': ['kio_id', 'llm', 'source', 'task_type'],
                         'required_group_by': [],
                         'supports_source': True},
 'kio.cross_arch_build.success_count': {'otel_name': 'kio.cross_arch_build.success_count',
                                        'prom_name': 'kio_cross_arch_build_success_count',
                                        'instrument': 'counter',
                                        'unit': '1',
                                        'family': 'kpi',
                                        'roles': ['green-deploy'],
                                        'optional': True,
                                        'requires_task_type': [],
                                        'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                        'required_group_by': [],
                                        'supports_source': True},
 'kio.deploy_energy.tokens_per_s_per_w': {'otel_name': 'kio.deploy_energy.tokens_per_s_per_w',
                                          'prom_name': 'kio_deploy_energy_tokens_per_s_per_w',
                                          'instrument': 'histogram',
                                          'unit': '1',
                                          'family': 'kpi',
                                          'roles': ['green-deploy'],
                                          'optional': True,
                                          'requires_task_type': [],
                                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                          'required_group_by': [],
                                          'supports_source': True},
 'kio.dev_productivity.features_per_day': {'otel_name': 'kio.dev_productivity.features_per_day',
                                           'prom_name': 'kio_dev_productivity_features_per_day',
                                           'instrument': 'histogram',
                                           'unit': '1',
                                           'family': 'kpi',
                                           'roles': ['ai-sysdev'],
                                           'optional': True,
                                           'requires_task_type': [],
                                           'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                           'required_group_by': [],
                                           'supports_source': True},
 'kio.fix.attempt_count': {'otel_name': 'kio.fix.attempt_count',
                           'prom_name': 'kio_fix_attempt_count',
                           'instrument': 'counter',
                           'unit': '1',
                           'family': 'kpi',
                           'roles': ['bugfix'],
                           'optional': True,
                           'requires_task_type': [],
                           'labels': ['kio_id', 'llm', 'outcome', 'source', 'task_type'],
                           'required_group_by': ['outcome'],
                           'supports_source': True},
 'kio.heartbeat': {'otel_name': 'kio.heartbeat',
                   'prom_name': 'kio_heartbeat',
                   'instrument': 'counter',
                   'unit': '1',
                   'family': 'operational',
                   'roles': [],
                   'optional': False,
                   'requires_task_type': [],
                   'labels': ['kio_id', 'llm', 'task_type'],
                   'required_group_by': [],
                   'supports_source': False},
 'kio.issue.customer_reported_count': {'otel_name': 'kio.issue.customer_reported_count',
                                       'prom_name': 'kio_issue_customer_reported_count',
                                       'instrument': 'counter',
                                       'unit': '1',
                                       'family': 'kpi',
                                       'roles': ['bugfix'],
                                       'optional': True,
                                       'requires_task_type': [],
                                       'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                       'required_group_by': [],
                                       'supports_source': True},
 'kio.issue.resolution_hours': {'otel_name': 'kio.issue.resolution_hours',
                                'prom_name': 'kio_issue_resolution_hours',
                                'instrument': 'histogram',
                                'unit': 'h',
                                'family': 'kpi',
                                'roles': ['bugfix'],
                                'optional': True,
                                'requires_task_type': [],
                                'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                'required_group_by': [],
                                'supports_source': True},
 'kio.lifecycle_energy.pct_of_baseline': {'otel_name': 'kio.lifecycle_energy.pct_of_baseline',
                                          'prom_name': 'kio_lifecycle_energy_pct_of_baseline',
                                          'instrument': 'histogram',
                                          'unit': '%',
                                          'family': 'kpi',
                                          'roles': ['green-deploy'],
                                          'optional': True,
                                          'requires_task_type': [],
                                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                          'required_group_by': [],
                                          'supports_source': True},
 'kio.llm.cost_usd': {'otel_name': 'kio.llm.cost_usd',
                      'prom_name': 'kio_llm_cost_usd',
                      'instrument': 'counter',
                      'unit': 'USD',
                      'family': 'operational',
                      'roles': [],
                      'optional': False,
                      'requires_task_type': [],
                      'labels': ['kio_id', 'llm', 'source', 'task_type'],
                      'required_group_by': [],
                      'supports_source': True},
 'kio.llm.energy_joules': {'otel_name': 'kio.llm.energy_joules',
                           'prom_name': 'kio_llm_energy_joules',
                           'instrument': 'counter',
                           'unit': 'J',
                           'family': 'operational',
                           'roles': [],
                           'optional': False,
                           'requires_task_type': [],
                           'labels': ['kio_id', 'llm', 'source', 'task_type'],
                           'required_group_by': [],
                           'supports_source': True},
 'kio.llm.gpu_temperature_celsius': {'otel_name': 'kio.llm.gpu_temperature_celsius',
                                     'prom_name': 'kio_llm_gpu_temperature_celsius',
                                     'instrument': 'histogram',
                                     'unit': 'Cel',
                                     'family': 'operational',
                                     'roles': [],
                                     'optional': False,
                                     'requires_task_type': [],
                                     'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                     'required_group_by': [],
                                     'supports_source': True},
 'kio.llm.token_count': {'otel_name': 'kio.llm.token_count',
                         'prom_name': 'kio_llm_token_count',
                         'instrument': 'counter',
                         'unit': 'tokens',
                         'family': 'operational',
                         'roles': [],
                         'optional': False,
                         'requires_task_type': [],
                         'labels': ['direction', 'kio_id', 'llm', 'source', 'task_type'],
                         'required_group_by': ['direction'],
                         'supports_source': True},
 'kio.llm.tokens_per_second': {'otel_name': 'kio.llm.tokens_per_second',
                               'prom_name': 'kio_llm_tokens_per_second',
                               'instrument': 'histogram',
                               'unit': 'tokens/s',
                               'family': 'operational',
                               'roles': [],
                               'optional': False,
                               'requires_task_type': [],
                               'labels': ['kio_id', 'llm', 'source', 'task_type'],
                               'required_group_by': [],
                               'supports_source': True},
 'kio.refactoring.hours_per_feature': {'otel_name': 'kio.refactoring.hours_per_feature',
                                       'prom_name': 'kio_refactoring_hours_per_feature',
                                       'instrument': 'histogram',
                                       'unit': 'h',
                                       'family': 'kpi',
                                       'roles': ['ai-sysdev'],
                                       'optional': True,
                                       'requires_task_type': [],
                                       'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                       'required_group_by': [],
                                       'supports_source': True},
 'kio.repo.directory_count': {'otel_name': 'kio.repo.directory_count',
                              'prom_name': 'kio_repo_directory_count',
                              'instrument': 'gauge',
                              'unit': '1',
                              'family': 'operational',
                              'roles': [],
                              'optional': True,
                              'requires_task_type': ['code-analysis'],
                              'labels': ['kio_id', 'llm', 'task_type'],
                              'required_group_by': [],
                              'supports_source': False},
 'kio.repo.file_count': {'otel_name': 'kio.repo.file_count',
                         'prom_name': 'kio_repo_file_count',
                         'instrument': 'gauge',
                         'unit': '1',
                         'family': 'operational',
                         'roles': [],
                         'optional': True,
                         'requires_task_type': ['code-analysis'],
                         'labels': ['kio_id', 'llm', 'task_type'],
                         'required_group_by': [],
                         'supports_source': False},
 'kio.repo.line_count': {'otel_name': 'kio.repo.line_count',
                         'prom_name': 'kio_repo_line_count',
                         'instrument': 'gauge',
                         'unit': '1',
                         'family': 'operational',
                         'roles': [],
                         'optional': True,
                         'requires_task_type': ['code-analysis'],
                         'labels': ['kio_id', 'llm', 'task_type'],
                         'required_group_by': [],
                         'supports_source': False},
 'kio.request.accuracy': {'otel_name': 'kio.request.accuracy',
                          'prom_name': 'kio_request_accuracy',
                          'instrument': 'histogram',
                          'unit': '1',
                          'family': 'operational',
                          'roles': [],
                          'optional': False,
                          'requires_task_type': [],
                          'labels': ['kio_id', 'llm', 'source', 'task_type'],
                          'required_group_by': [],
                          'supports_source': True},
 'kio.request.count': {'otel_name': 'kio.request.count',
                       'prom_name': 'kio_request_count',
                       'instrument': 'counter',
                       'unit': '1',
                       'family': 'operational',
                       'roles': [],
                       'optional': False,
                       'requires_task_type': [],
                       'labels': ['kio_id', 'llm', 'source', 'status', 'task_type'],
                       'required_group_by': ['status'],
                       'supports_source': True},
 'kio.request.duration_ms': {'otel_name': 'kio.request.duration_ms',
                             'prom_name': 'kio_request_duration_ms',
                             'instrument': 'histogram',
                             'unit': 'ms',
                             'family': 'operational',
                             'roles': [],
                             'optional': False,
                             'requires_task_type': [],
                             'labels': ['kio_id', 'llm', 'source', 'task_type'],
                             'required_group_by': [],
                             'supports_source': True},
 'kio.request.error_count': {'otel_name': 'kio.request.error_count',
                             'prom_name': 'kio_request_error_count',
                             'instrument': 'counter',
                             'unit': '1',
                             'family': 'operational',
                             'roles': [],
                             'optional': False,
                             'requires_task_type': [],
                             'labels': ['error_type', 'kio_id', 'llm', 'source', 'task_type'],
                             'required_group_by': ['error_type'],
                             'supports_source': True},
 'kio.review.score': {'otel_name': 'kio.review.score',
                      'prom_name': 'kio_review_score',
                      'instrument': 'histogram',
                      'unit': '1',
                      'family': 'kpi',
                      'roles': ['architecture-to-code'],
                      'optional': True,
                      'requires_task_type': [],
                      'labels': ['kio_id', 'llm', 'source', 'task_type'],
                      'required_group_by': [],
                      'supports_source': True},
 'kio.session.active_count': {'otel_name': 'kio.session.active_count',
                              'prom_name': 'kio_session_active_count',
                              'instrument': 'up_down_counter',
                              'unit': '1',
                              'family': 'operational',
                              'roles': [],
                              'optional': False,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'task_type'],
                              'required_group_by': [],
                              'supports_source': False},
 'kio.slicing.success_rate': {'otel_name': 'kio.slicing.success_rate',
                              'prom_name': 'kio_slicing_success_rate',
                              'instrument': 'histogram',
                              'unit': '1',
                              'family': 'kpi',
                              'roles': ['bugfix'],
                              'optional': True,
                              'requires_task_type': [],
                              'labels': ['kio_id', 'llm', 'source', 'task_type'],
                              'required_group_by': [],
                              'supports_source': True},
 'kio.tech_debt.hours_per_100loc': {'otel_name': 'kio.tech_debt.hours_per_100loc',
                                    'prom_name': 'kio_tech_debt_hours_per_100loc',
                                    'instrument': 'histogram',
                                    'unit': 'h',
                                    'family': 'kpi',
                                    'roles': ['ai-sysdev'],
                                    'optional': True,
                                    'requires_task_type': [],
                                    'labels': ['kio_id', 'llm', 'source', 'task_type'],
                                    'required_group_by': [],
                                    'supports_source': True},
 'kio.time_to_market.days': {'otel_name': 'kio.time_to_market.days',
                             'prom_name': 'kio_time_to_market_days',
                             'instrument': 'histogram',
                             'unit': 'd',
                             'family': 'kpi',
                             'roles': ['ai-sysdev'],
                             'optional': True,
                             'requires_task_type': [],
                             'labels': ['kio_id', 'llm', 'source', 'task_type'],
                             'required_group_by': [],
                             'supports_source': True}}
