"""Build the all-KPI attainment section on the Overview dashboard.

Regenerate with:
    python scripts/generate_overview_kpis.py

Idempotent: strips any panel a previous run added (ids 200-299) and rebuilds
the section at the top of grafana/dashboards/ai4sweng-overview.json.

The section answers one question — *how much of each D1.1 target has been
reached* — aggregated across every reporting KIO (no kio_id filter; this is the
all-KIOs page). Definitions, targets and directions come from
scripts/d11_kpis.py.

Because kio_simulator.py now emits every KPI in D1.1's own unit, every KPI is
directly comparable to its target and all of them appear in one list. There is
no longer a separate group of KPIs that could not be scored.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import d11_kpis as d11  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OVERVIEW = REPO / "grafana" / "dashboards" / "ai4sweng-overview.json"

DS = {"type": "prometheus", "uid": "victoriametrics"}


def ref_id(i: int) -> str:
    return chr(65 + i) if i < 26 else f"Q{i}"


def main() -> None:
    d = json.loads(OVERVIEW.read_text(encoding="utf-8"))
    d["panels"] = [p for p in d["panels"] if not (200 <= p.get("id", 0) < 300)]

    kpis = d11.KPIS

    banner = {
        "id": 200,
        "type": "text",
        "title": "",
        "transparent": True,
        "gridPos": {"h": 3, "w": 24, "x": 0, "y": 0},
        "options": {
            "mode": "markdown",
            "content": (
                "### D1.1 Project KPIs — attainment against target\n"
                "**⚠ SIMULATED DATA.** No real KIO module reports these yet; every value "
                "below is generated by `kio-simulator/kio_simulator.py` within D1.1's "
                "baseline/target bands. These are *not* project results. "
                "Real values will arrive tagged `source=real` as KIO owners connect."
            ),
        },
    }

    bar = {
        "id": 201,
        "type": "bargauge",
        "title": "Attainment — 100% means the D1.1 target is met (all KIOs, SIMULATED)",
        "description": (
            "Each KPI is normalised against its own D1.1 target so one axis covers "
            "all of them:\n\n"
            "- lower-is-better KPIs: `100 x target / measured`\n"
            "- higher-is-better KPIs: `100 x measured / target`\n\n"
            "Green = target met or beaten (>=100%), amber = within 20% of it, red = "
            "below, grey = no KIO currently reporting it.\n\n"
            "D1.1 states almost every KPI as a percentage of baseline (baseline = "
            "100%), and the simulator emits them in that unit — so no unit conversion "
            "or baseline midpoint is assumed anywhere. Averaged over the dashboard "
            "time range."
        ),
        "datasource": DS,
        "gridPos": {"h": 15, "w": 24, "x": 0, "y": 3},
        "fieldConfig": {
            "defaults": {
                "unit": "percent",
                "decimals": 0,
                "min": 0,
                "max": 150,
                "noValue": "no producer",
                "mappings": [{
                    "type": "range",
                    "options": {
                        "from": -1000000,
                        "to": 0,
                        "result": {"text": "no producer", "color": "#585A5E", "index": 0},
                    },
                }],
                "thresholds": {
                    "mode": "absolute",
                    "steps": [
                        {"color": "red", "value": None},
                        {"color": "orange", "value": 80},
                        {"color": "green", "value": 100},
                    ],
                },
            },
            "overrides": [],
        },
        "options": {
            "displayMode": "basic",
            "orientation": "horizontal",
            "showUnfilled": True,
            "valueMode": "color",
            "minVizWidth": 8,
            "minVizHeight": 16,
            "namePlacement": "left",
            "sizing": "auto",
            "legend": {"showLegend": False},
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
        },
        "targets": [
            {
                "refId": ref_id(i),
                "datasource": DS,
                "editorMode": "code",
                "expr": k.attainment_expr(),
                "legendFormat": f"KPI {k.kpi_id} {k.name}  (target {k.target_text})",
                "range": False,
                "instant": True,
            }
            for i, k in enumerate(kpis)
        ],
    }

    values = {
        "id": 202,
        "type": "bargauge",
        "title": "Measured value in D1.1's own unit (all KIOs, SIMULATED)",
        "description": (
            "The raw measurement behind each attainment bar, in the unit D1.1 "
            "specifies — percent of baseline for all but KPI 8.1 (% of eligible "
            "users), 8.2 (% of users, and MOS 1-5) and 8.3 (a count). Each bar is "
            "coloured against that KPI's own target, so green here means the same "
            "thing as green above."
        ),
        "datasource": DS,
        "gridPos": {"h": 15, "w": 24, "x": 0, "y": 18},
        "fieldConfig": {
            "defaults": {
                "unit": "percent",
                "decimals": 1,
                "min": 0,
                "noValue": "no producer",
                "thresholds": {"mode": "absolute", "steps": [{"color": "text", "value": None}]},
            },
            # Each KPI needs its own target colouring, and KPI 8.2's MOS and
            # KPI 8.3's count are not percentages — so every series is overridden
            # by name rather than sharing the panel default.
            "overrides": [
                {
                    "matcher": {"id": "byName", "options": f"KPI {k.kpi_id} {k.name}"},
                    "properties": [
                        {"id": "unit", "value": k.unit},
                        {"id": "thresholds", "value": {"mode": "absolute", "steps": k.thresholds()}},
                    ],
                }
                for k in kpis
            ],
        },
        "options": {
            "displayMode": "basic",
            "orientation": "horizontal",
            "showUnfilled": True,
            "valueMode": "color",
            "minVizWidth": 8,
            "minVizHeight": 16,
            "namePlacement": "left",
            "sizing": "auto",
            "legend": {"showLegend": False},
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
        },
        "targets": [
            {
                "refId": ref_id(i),
                "datasource": DS,
                "editorMode": "code",
                "expr": f"({k.value_expr()}) or vector(-1)",
                "legendFormat": f"KPI {k.kpi_id} {k.name}",
                "range": False,
                "instant": True,
            }
            for i, k in enumerate(kpis)
        ],
    }

    top = [banner, bar, values]
    offset = 33

    rows = sorted({p["gridPos"]["y"] for p in d["panels"]})
    remap: dict[int, int] = {}
    cur = offset
    for oy in rows:
        remap[oy] = cur
        cur += max(p["gridPos"]["h"] for p in d["panels"] if p["gridPos"]["y"] == oy)
    for p in d["panels"]:
        p["gridPos"]["y"] = remap[p["gridPos"]["y"]]

    d["panels"] = top + d["panels"]
    d["version"] = d.get("version", 1) + 1
    OVERVIEW.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"KPI series on the overview: {len(kpis)} (every D1.1 global KPI, none excluded)")
    for k in kpis:
        arrow = "<=" if k.direction != d11.HIGHER else ">="
        print(f"  KPI {k.kpi_id:4} {k.name:32} {arrow}{k.target:<6} [{k.unit}]  {k.direction}")
    print(f"\npanels now on the overview: {len(d['panels'])}")


if __name__ == "__main__":
    main()
